import:
    # Experiment
    - 'experiments/simple_depoly.yaml'

    # Model
    - 'components/barbed_polymerization_depoly.yaml'
#    - 'components/pi_release_in_solution.yaml'
#    - 'components/pi_association.yaml'
    - 'components/fast_pi_tip_release.yaml'

    # Parameters
    - 'parameters/jegou_2011_conditions.yaml'
    - 'parameters/first_paper.yaml'
#    - 'parameters/tip_release_rate.yaml'

experiments:
    simple_depoly:
        parameters:
            simulation_duration: 1300.01
            polymerization_duration: 300
            sample_period: 1

            pointed_tip_release_rate: 0
