# Polymerization/Depolymerization parameters
barbed_atp_polymerization_rate:   [11.6, 11.6, 1, linear]
barbed_adppi_polymerization_rate: [ 3.4,  3.4, 1, linear]
barbed_adp_polymerization_rate:   [ 2.9,  2.9, 1, linear]

barbed_atp_depolymerization_rate:   [1.4, 1.4, 1, linear]
barbed_adppi_depolymerization_rate: [0.2, 0.2, 1, linear]
barbed_adp_depolymerization_rate:   [5.4, 5.4, 1, linear]


pointed_atp_polymerization_rate:   [1.3,  1.3,  1, linear]
pointed_adppi_polymerization_rate: [0.11, 0.11, 1, linear]
pointed_adp_polymerization_rate:   [0.14, 0.14, 1, linear]

pointed_atp_depolymerization_rate:   [0.8,  0.8,  1, linear]
pointed_adppi_depolymerization_rate: [0.02, 0.02, 1, linear]
pointed_adp_depolymerization_rate:   [0.25, 0.25, 1, linear]


# Hydrolysis parameters
cleavage_rate: [0.05, 1.00, 10, linear]
cleavage_cooperativity: [1, 3000000, 10, log]

release_rate: [0.003, 0.003, 1, linear]


# Initial Strand
seed_concentration: [6, 6, 1, linear]


# Concentrations
# Pollard's value
#filament_tip_concentration: [0.0112, 0.0112, 1, linear]
# Frank's value
#filament_tip_concentration: [0.0224, 0.0224, 1, linear]

filament_tip_concentration: [0.005, 0.050, 10, linear]


initial_atp_concentration: [6, 6, 1, linear]
initial_adp_concentration: [0, 0, 1, linear]

initial_adppi_concentration: [0, 0, 1, linear]
initial_pi_concentration:    [0, 0, 1, linear]


# End Conditions
simulation_duration: [40, 40, 1, linear]


# Simulation Parameters
sample_period: [0.5, 0.5, 1, linear]
number_of_filaments: [6, 6, 1, linear]
number_of_simulations: [10, 10, 1, linear]
