import:
    # Experiment
    - 'experiments/elongation_rate.yaml'

    # Core Model
    - 'components/barbed_polymerization.yaml'
    - 'components/pointed_polymerization.yaml'
    - 'components/pi_release_in_solution.yaml'
    - 'components/pi_association.yaml'
    - 'components/fast_pi_tip_release.yaml'

    # Parameters
    - 'parameters/polymerization_fujiwara_full.yaml'
    - 'parameters/tip_release_rate.yaml'

global_parameters:
    sample_period: 1

    simulation_duration: 2000
    analysis_time: 1000

    seed_concentration: 30
    filament_tip_concentration: 0.001

    cleavage_rate: 0.3

    number_of_filaments: 100

parameter_specifications:
    elongation_rate:
        simulation:
            actin_concentration:
                lower_bound: 0.01
                upper_bound: 0.5
                mesh_type: linear
                num_points: 100
