import:
    # Experiment
    - 'experiments/adp_copoly.yaml'

    # Parameters
    - 'parameters/melki_conditions.yaml'
    - 'parameters/melki_fnc.yaml'
    - 'parameters/first_paper.yaml'
    - 'parameters/tip_release_rate.yaml'
#    - 'parameters/small_statistics.yaml'
#    - 'parameters/medium_statistics.yaml'

experiments:
    adp_copoly:
        parameters:
            simulation_duration: 500
            sample_period: 0.1

            number_of_simulations: 100
            number_of_filaments: 1

parameter_specifications:
    adp_copoly:
        simulation:
            fraction_adp:
                lower_bound: 0.005
                upper_bound: 0.5
                mesh_type: log
                num_points: 31
