import:
    # Experiment
    - 'experiments/adp_copoly.yaml'

    # Parameters
    - 'parameters/melki_conditions.yaml'
    - 'parameters/first_paper.yaml'
    - 'parameters/medium_statistics.yaml'

experiments:
    adp_copoly:
        parameters:
            simulation_duration: 500
            sample_period: 0.5

parameter_specifications:
    adp_copoly:
        simulation:
            fraction_adp:
                lower_bound: 0.001
                upper_bound: 0.1
                mesh_type: log
                num_points: 16
