import:
    # Experiment
    - 'experiments/tagged_pi_poly.yaml'

    # Parameters
    - 'parameters/melki_fnc.yaml'
    - 'parameters/melki_conditions.yaml'
    - 'parameters/first_paper.yaml'
    - 'parameters/tip_release_rate.yaml'

experiments:
    pi_poly:
        parameters:
            simulation_duration: 3600.1
            asymptotic_time: 3600

            sample_period: 1

            number_of_simulations: 10
            number_of_filaments: 1


parameter_specifications:
    pi_poly:
        simulation:
            initial_pi_concentration:
                lower_bound: 1000
                upper_bound: 1000000
                mesh_type: log
                num_points: 21
