import:
    - 'experiments/pyrene_depoly.yaml'
    - 'random_cooperative_model_concentration_depoly.yaml'

    # Parameters
    - 'parameters/jegou_2011_conditions.yaml'
    - 'parameters/first_paper.yaml'
    - 'parameters/brooks_pyrene_coefficients.yaml'
#    - 'parameters/medium_statistics.yaml'
    - 'parameters/small_statistics.yaml'

experiments:
    pyrene_depoly:
        parameters:
            simulation_duration: 1600
            sample_period: 0.5
            depoly_threshold: 0.375 # 75% polymerized
#            depoly_threshold: 1.2 # 20% polymerized

parameter_specifications:
    pyrene_depoly:
        simulation:
            dummy_parameter:
                lower_bound: 1
                upper_bound: 1
                mesh_type: linear
                num_points: 1
