import:
    # Experiment
    - 'experiments/halftime_sensitivity.yaml'

    # Parameters
    - 'parameters/melki_conditions.yaml'
    - 'parameters/melki_fnc.yaml'
    - 'parameters/first_paper.yaml'
    - 'parameters/tip_release_rate.yaml'

global_parameters:
    number_of_simulations: 150
    number_of_filaments: 1

    simulation_duration: 500.0

    sample_period: 0.1
