import:
    # Experiment
    - 'experiments/halftime_sensitivity.yaml'

    # Parameters
    - 'parameters/melki_conditions.yaml'
    - 'parameters/first_paper.yaml'
    - 'parameters/big_statistics.yaml'

global_parameters:
    simulation_duration: 500.0

    sample_period: 0.1
